project:
  type: sdca-theme

website:
  title: "SDCA Research"
  site-url: "https://steno-aarhus.github.io/research/"
  repo-url: "https://github.com/steno-aarhus/research"
  body-footer: |
    ::: callout-note
    This website and the documents contained within are aimed at researchers,
    PhD students, staff, and external collaborators.
    :::
  page-footer:
    center:
      - text: "Accessibility statement"
        href: https://www.was.digst.dk/steno-aarhus-github-io-research-
  navbar:
    pinned: true
    left:
      - text: "About"
        menu:
          - href: about/index.md
          - href: about/github.md
          - href: about/quarto.md
      - text: "Common docs"
        menu:
          - text: "Onboarding"
            href: onboarding.md
          - text: "Support"
            href: support.md
          - text: "Organization"
            href: organization.md
      - text: "Contributing"
        menu:
          - text: "Guidelines"
            href: CONTRIBUTING.md
          - text: "Code of Conduct"
            href: CODE_OF_CONDUCT.md
    tools:
      - icon: github
        href: "https://github.com/steno-aarhus/research"
        aria-label: "GitHub icon: Link to the SDCA Research repository page"
      - icon: twitter
        href: "https://twitter.com/StenoAarhusRes"
        aria-label: "Twitter icon: Link to SDCA Twitter page"

format:
  sdca-theme-html:
    theme:
      - sdca-theme-html
      - style.scss

editor:
  markdown:
    wrap: 72
    canonical: true
